before_install:
  - |
    # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
    [[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/
    curl -sL https://get.sdkman.io | bash
    echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
    echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
    source $HOME/.sdkman/bin/sdkman-init.sh
    sdkJava=$(sdk list java | grep -o " $ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1 | cut -c2-)
    # if we didn't find AdoptOpenJDK, accept a non-Adopt early access build
    if [[ -z $sdkJava ]]; then sdkJava=$(sdk list java | egrep -o " $ADOPTOPENJDK\\.ea.[0-9]+-open" | head -1 | cut -c2-); fi
    if [[ -z $sdkJava ]]; then echo "no matching JDK found: $ADOPTOPENJDK"; travis_terminate 1; fi
    sdk install java $sdkJava || true # install fails if it's already installed
    sdk use java $sdkJava
    unset JAVA_HOME
    if [[ $ADOPTOPENJDK == 8 ]]; then versionPrefix="1\.8"; else versionPrefix=$ADOPTOPENJDK; fi
    java -version
  - java -version 2>&1 | grep 'OpenJDK.*[^0-9]'$versionPrefix'[^0-9]' || exit 1
  # Travis-CI has (as of March 2021, anyway) an outdated sbt-extras version,
  # so overwrite it with a March 2021 version that works with sbt 1.4.8+
  - |
    curl -sL https://raw.githubusercontent.com/paulp/sbt-extras/dc4f350f112580fcdf5f6fa7e8d5d2116475f84a/sbt  > /tmp/sbt-launch-script || travis_terminate 1
    chmod +x /tmp/sbt-launch-script || travis_terminate 1
    sudo mv /tmp/sbt-launch-script /usr/local/bin/sbt || travis_terminate 1

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - rm -fv $HOME/.sdkman/var/broadcast
  - rm -fv $HOME/.sdkman/var/broadcast_id
  - find $HOME/.ivy2/cache -name "ivydata-*.properties"     -print -delete
  - find $HOME/.sbt        -name "*.lock"                   -print -delete
  - find $HOME/.sbt        -name "*compiler-bridge_*-bin-*" -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.sdkman
    - $HOME/.cache/coursier
