before_install:
  - |
    # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
    [[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/
    curl -sL https://get.sdkman.io | bash
    echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
    echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
    source $HOME/.sdkman/bin/sdkman-init.sh
    sdkJava=$(sdk list java | grep -o " $ADOPTOPENJDK\.[0-9\.]*-tem" | head -1 | cut -c2-)
    # if we didn't find Temurin, accept an early access build from Java.net
    if [[ -z $sdkJava ]]; then sdkJava=$(sdk list java | egrep -o " $ADOPTOPENJDK\\.ea.[0-9]+-open" | head -1 | cut -c2-); fi
    if [[ -z $sdkJava ]]; then sdk list java; echo "no matching JDK found: $ADOPTOPENJDK"; travis_terminate 1; fi
    sdk install java $sdkJava || true # install fails if it's already installed
    sdk use java $sdkJava
    unset JAVA_HOME
    if [[ $ADOPTOPENJDK == 8 ]]; then versionPrefix="1\.8"; else versionPrefix=$ADOPTOPENJDK; fi
    java -version
  - java -version 2>&1 | grep 'OpenJDK.*[^0-9]'$versionPrefix'[^0-9]' || exit 1
  # Travis-CI's default is an outdated version of sbt-extras;
  # overwrite it with the official sbt launcher
  - |
    unset SBT_OPTS
    unset JVM_OPTS
    unset SBT_ETC_FILE
    curl -L --silent "https://raw.githubusercontent.com/sbt/sbt/1.5.x/sbt" > $HOME/sbt
    chmod +x $HOME/sbt && sudo mv $HOME/sbt /usr/local/bin/sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - rm -fv $HOME/.sdkman/var/broadcast
  - rm -fv $HOME/.sdkman/var/broadcast_id
  - find $HOME/.ivy2/cache -name "ivydata-*.properties"     -print -delete
  - find $HOME/.sbt        -name "*.lock"                   -print -delete
  - find $HOME/.sbt        -name "*compiler-bridge_*-bin-*" -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.sdkman
    - $HOME/.cache/coursier
